# Generated by Django 5.1 on 2024-08-14 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='EN', max_length=10)),
                ('bot_profile_picture', models.CharField(max_length=10)),
                ('automated_response', models.BooleanField(default=True)),
                ('personalized_assistance', models.BooleanField(default=True)),
                ('live_chat_support', models.BooleanField(default=True)),
                ('sentiment_analysis', models.BooleanField(default=True)),
                ('faq_bot', models.BooleanField(default=True)),
                ('multi_lingual_support', models.BooleanField(default=True)),
                ('security_compliance', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
